language: python
sudo: required
dist: xenial
python:
    - '3.7'
    - '3.6'
matrix:
    fast_finish: true

notifications:
    email:
        recipients:
            - firefighterblu3@gmail.com
        on_success: always

install:
    - pip install flake8 pytest pytest-cov

script:
    - flake8 --exclude venv* --statistics
    - pytest -v --cov=lkml
